openapi: 3.1.0
info:
  title: Vendomatic API
  version: 0.0.1
servers:
  - url: https://vendomatic.evertras.com/api/v1
paths:
  /machines:
    get:
      summary: Get all machines
      operationId: getMachines
      responses:
        '200':
          description: List of machines
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MachineListResponse'
    post:
      summary: Create a new machine
      operationId: createMachine
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MachineCreateRequest'
      responses:
        '201':
          description: Machine created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MachineCreateResponse'
  /machines/{id}:
    get:
      summary: Get a machine by ID
      operationId: getMachineById
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the machine to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Machine details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MachineDetails'
        '404':
          description: Machine not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericErrorResponse'
    delete:
      summary: Delete a machine
      operationId: deleteMachine
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the machine to delete
          schema:
            type: string
      responses:
        '204':
          description: Machine deleted
  /machines/{id}/inventory:
    put:
      summary: Update machine inventory
      operationId: updateMachineInventory
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the machine to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MachineRestockRequest'
      responses:
        '200':
          description: Inventory updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MachineRestockResponse'

components:
  schemas:
    Machine:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
          minLength: 1
          maxLength: 100

    MachineInventoryEntry:
      type: object
      required:
        - name
        - quantity
        - costPennies
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        quantity:
          type: integer
          minimum: 0
        costPennies:
          type: integer
          minimum: 0

    MachineDetails:
      type: object
      required:
        - id
        - name
        - inventory
      properties:
        id:
          type: string
        name:
          type: string
          minLength: 1
          maxLength: 100
        inventory:
          type: array
          items:
            $ref: '#/components/schemas/MachineInventoryEntry'

    MachineDetailsResponse:
      type: object
      required:
        - machine
      properties:
        machine:
          $ref: '#/components/schemas/MachineDetails'

    MachineCreateRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100

    MachineCreateResponse:
      type: object
      required:
        - machine
      properties:
        machine:
          $ref: '#/components/schemas/Machine'

    MachineListResponse:
      type: object
      required:
        - machines
      properties:
        machines:
          type: array
          items:
            $ref: '#/components/schemas/Machine'

    MachineDeleteResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean

    MachineRestockRequest:
      type: object
      required:
        - inventory
      properties:
        inventory:
          type: array
          items:
            type: object
            required:
              - name
              - quantityTarget
              - costPennies
            properties:
              name:
                type: string
                minLength: 1
                maxLength: 100
              quantityTarget:
                type: integer
                minimum: 1
              costPennies:
                type: integer
                minimum: 1

    MachineRestockResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean

    GenericErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
